### ISSUE TITLE
GlobalWeather test always fails

### ISSUE THREAD

**Issue by geckon** [qorelanguage/module-xml#136]
GlobalWeather depends on [http://www.webservicex.com/globalweather.asmx](http://www.webservicex.com/globalweather.asmx) which currently returns
`{"code":"PAGE_NOT_FOUND","message":"Page not found"}`
And thus the test fails.

I suggest disabling the test at least for now and maybe removing it later if the service doesn't get back up. Or maybe we can even remove it completely to get rid of a test dependent on an external resource.

**Comment by omusil24** [comment]
Test is disabled now.
