### ISSUE TITLE
The wsdl module fails to parse the SalesDataInterface_v13.wsdl file.

### ISSUE THREAD

**Issue by martin-zemek** [qorelanguage/module-xml#35]
The error can be reproduced by running the following simple script:

```
#! /usr/bin/env qore
%requires SoapClient
%new-style

ReadOnlyFile f('<a_path_to>/SalesDataInterface_v13.wsdl');
my string s = f.read(-1);
WebService w(s);
```

**Comment by davidnich** [comment]
@martin-zemek please don't open issues for modules in the module repo - we open all issues (also for modules) in the Qore repo - see https://github.com/qorelanguage/qore/wiki/QA#issue-tracking for more info
